version: "3"

services:
  halo:
    image: halohub/halo:2.11
    restart: always
    container_name: halo
    restart: on-failure:3
    depends_on:
      halodb:
        condition: service_healthy
    networks:
      - traefik_network
      - halo_network
    volumes:
      - ./:/root/.halo2
      - /etc/localtime:/etc/localtime
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health/readiness"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s          
    command:
      - --spring.r2dbc.url=r2dbc:pool:postgresql://halodb/halo
      - --spring.r2dbc.username=ccopspostgresql
      # PostgreSQL 的密码，请保证与下方 POSTGRES_PASSWORD 的变量值一致。
      - --spring.r2dbc.password=tHg6voaWFa!SXgUh
      - --spring.sql.init.platform=postgresql
      # 外部访问地址，请根据实际需要修改
      - --halo.external-url=http://www.ccops.cc/
      # 初始化的超级管理员用户名
      - --halo.security.initializer.superadminusername=caicai-admin
      # 初始化的超级管理员密码
      - --halo.security.initializer.superadminpassword=pVD_vTy-v7T8zCr
      - -e TZ=Asia/Shanghai
    labels:
      traefik.enable: "true"
      traefik.http.routers.halo.rule: Host(`www.ccops.cc`)
      traefik.http.routers.halo.tls: "true"
      traefik.http.routers.halo.tls.certresolver: myresolver
      traefik.http.services.halo.loadbalancer.server.port: 8090
  halodb:
    image: postgres:15.4
    restart: always
    container_name: halodb
    restart: on-failure:3
    networks:
      - halo_network
    volumes:
      - ./db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=tHg6voaWFa!SXgUh
      - POSTGRES_USER=ccopspostgresql
      - POSTGRES_DB=halo
      - PGUSER=halo
networks:
  halo_network:
    name: halo_network
  traefik_network:
    external: true
