services:   
  kibana:
    restart: always
    image: ccr.ccs.tencentyun.com/ccops/all:kibana-7.10.2
    container_name: kibana
    ports:
        - 5601:5601
    privileged: true
    environment:
      - "TZ=Asia/Shanghai"
      - "I18N_LOCALE=zh-CN"
      - "ELASTICSEARCH_HOSTS=http://192.168.10.143:9200"
      - "ELASTICSEARCH_USERNAME=esadmin"
      - "ELASTICSEARCH_PASSWORD=qweasd"
    healthcheck:
      test: ["CMD-SHELL", "curl -sS http://localhost:5601/api/status | grep -q '\"overall\":{\"level\":\"available\"}' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s