version: "3.8"
networks:
  app_network:
    name: app_network
    attachable: true
    driver: bridge
services:
  nginx:
    restart: always
    image: ccr.ccs.tencentyun.com/ccops/all:nginx-1.26.3
    pid: "service:nginx-ui"
    container_name: nginx
    networks:
      - app_network
    ports:
      - "88:80"
      - "4443:443"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/status"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./config/conf.d:/etc/nginx/conf.d
      - ./config/certs:/etc/nginx/certs
      - ./config/sites-enabled:/etc/nginx/sites-enabled
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - /data/hexo/public:/var/www/html
      - ./logs/:/var/log/nginx/
      - /etc/localtime:/etc/localtime
  nginx-ui:
    restart: always
    image: ccr.ccs.tencentyun.com/ccops/nginx-ui:2.0.0-rc5
    container_name: nginx-ui
    networks:
      - app_network
    volumes:
      - ./nginx-ui:/etc/nginx-ui
      - ./config/conf.d:/etc/nginx/conf.d
      - ./config/certs:/etc/nginx/ssl
      - ./config/sites-enabled:/etc/nginx/sites-enabled
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/:/var/log/nginx/
      - /etc/localtime:/etc/localtime