services:
  minio:
    restart: always
    privileged: true
    image: quay.io/minio/minio
    container_name: minio
    networks:
      - app_network
    command: server --console-address ":443" /data
    ports:
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=ccops_admin
      - MINIO_ROOT_PASSWORD=0$8VIoKOps2I0KfY
      - MINIO_DOMAIN=ccops.cc
    volumes:
      - /etc/localtime:/etc/localtime
      - ./minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:443/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  piclist:
    image: 'kuingsmile/piclist:latest'
    container_name: piclist
    restart: always
    networks:
      - app_network
    volumes:
      - ./piclist:/root/.piclist
      - /etc/localtime:/etc/localtime:ro
    command: node /usr/local/bin/picgo-server -k 1qaz@WSX
networks:
  app_network:
    external: true
    name: app_network