services:
  portainer:
    image: ccr.ccs.tencentyun.com/ccops/all:portainer-ce
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
      restart_policy:
        condition: on-failure
    volumes:
    - ./data:/data
    - /var/run/docker.sock:/var/run/docker.sock
