version: "3.8"
networks:
  traefik_network:
    name: traefik_network
  umami_network:
    name: umami_network
services:
  prometheus:
    image: dpage/pgadmin4:8.1
    container_name: pgadmin
    networks:
      - traefik_network
      - umami_network
    environment:
      - PGADMIN_DEFAULT_EMAIL=caicai@ccops.cc
      - PGADMIN_DEFAULT_PASSWORD=pVD_vTy-v7T8zCr
    volumes:
      - /etc/localtime:/etc/localtime
      - ./pgadmin_data:/var/lib/pgadmin
    labels:
      traefik.enable: "true"
      traefik.http.routers.prometheus.rule: Host(`tmp.ccops.cc`)
      traefik.http.routers.prometheus.tls: "true"
      traefik.http.routers.prometheus.tls.certresolver: myresolver
      traefik.http.services.prometheus.loadbalancer.server.port: 80
