services:
  traefik:
    restart: always
    image: traefik:v3.3.6
    container_name: traefik
    networks:
      - app_network
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: ["CMD", "wget", "--spider", "--no-check-certificate", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/logs
      - ./acme.json:/data/acme.json
      - ./traefik-conf.yaml:/etc/traefik/traefik-conf.yaml
      - ./services-rule:/etc/traefik/services-rule
      - /etc/localtime:/etc/localtime
    command:
      - --configFile=/etc/traefik/traefik-conf.yaml
networks:
  app_network:
    name: app_network
    attachable: true
    driver: bridge
