services:
  traefik:
    restart: always
    image: traefik:v3.3.6
    container_name: traefik
    networks:
      - app_network
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: ["CMD", "wget", "--spider", "--no-check-certificate", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/plugins-storage
      - ./services-rule:/etc/traefik/services-rule
      - /etc/localtime:/etc/localtime
    environment:
      - "TENCENTCLOUD_SECRET_ID= "
      - "TENCENTCLOUD_SECRET_KEY= "
    command:
      - --configFile=/plugins-storage/traefik-conf.yaml
networks:
  app_network:
    external: true
    name: app_network